### PR TITLE
fix setting ch_name for ECG (use auto)

### PR DESCRIPTION
**Pull request by agramfort**
disclaimer untested

### CODE REVIEW

**Comment by soichih** [comment]
I've updated the App configuration to set ch_type instead of ch_name.

image

@agramfort I've made you the administrator of the App so you can edit it on brainlife yourself.

**Comment by agramfort** [comment]
do I have a way to debug locally @soichih ?

**Comment by soichih** [comment]
It failed with this 

```
+ singularity exec -e docker://brainlife/mne:0.19.2 ./detect.py
[91mERROR  : Could not write to /N/soft/rhel7/singularity/2.6.1/var/singularity/mnt/final/etc/localtime: Too many levels of symbolic links
[0m./detect.py:14: RuntimeWarning: This filename (../5df9240dcc67236417bce230/5df9057b32bff04846e23445/meg.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz or _meg.fif
  raw = io.read_raw_fif(fname)
./detect.py:14: RuntimeWarning: Split raw file detected but next file /N/dc2/scratch/brlife/carbonate-workflows/5df9240dcc67231adbbce22f/5df9240dcc67236417bce230/5df9057b32bff04846e23445/meg-1.fif does not exist.
  raw = io.read_raw_fif(fname)
Traceback (most recent call last):
  File "./detect.py", line 27, in <module>
    evoked.plot(show=False)
AttributeError: 'numpy.ndarray' object has no attribute 'plot'
```

@agramfort Yes, you can download the testdata (you just need a .fif), and run the `main` anywhere that has singularity installed.

**Comment by soichih** [comment]
Actually, you can just point config.json to the sample MNE dataset's fif file?

You can copy config.json.sample to config.json and edit it to point to the test data.

**Pull request merged**
